// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestBackEnd.src.Data;

#nullable disable

namespace TestBackEnd.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestBackEnd.src.Models.Deliverer", b =>
                {
                    b.Property<string>("DelivererId")
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CNH")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("CNHImgPath")
                        .HasColumnType("text");

                    b.Property<string>("CNHType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DelivererId");

                    b.HasIndex("CNH")
                        .IsUnique();

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.ToTable("Deliverer", (string)null);
                });

            modelBuilder.Entity("TestBackEnd.src.Models.Motorcycle", b =>
                {
                    b.Property<string>("MotorcycleId")
                        .HasColumnType("text");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("MotorcycleId");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.ToTable("Motorcycles", (string)null);
                });

            modelBuilder.Entity("TestBackEnd.src.Models.Rental", b =>
                {
                    b.Property<Guid>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Days")
                        .HasColumnType("integer");

                    b.Property<string>("DelivererId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpectedEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotorcycleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RentalTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RentalId");

                    b.HasIndex("DelivererId");

                    b.HasIndex("MotorcycleId");

                    b.HasIndex("RentalTypeId");

                    b.ToTable("Rentals", (string)null);
                });

            modelBuilder.Entity("TestBackEnd.src.Models.RentalType", b =>
                {
                    b.Property<string>("RentalTypeId")
                        .HasColumnType("text");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<int>("Days")
                        .HasColumnType("integer");

                    b.HasKey("RentalTypeId");

                    b.ToTable("RentalTypes", (string)null);

                    b.HasData(
                        new
                        {
                            RentalTypeId = "1",
                            Cost = 30.00m,
                            Days = 7
                        },
                        new
                        {
                            RentalTypeId = "2",
                            Cost = 28.00m,
                            Days = 15
                        },
                        new
                        {
                            RentalTypeId = "3",
                            Cost = 22.00m,
                            Days = 30
                        },
                        new
                        {
                            RentalTypeId = "4",
                            Cost = 20.00m,
                            Days = 45
                        },
                        new
                        {
                            RentalTypeId = "5",
                            Cost = 18.00m,
                            Days = 50
                        });
                });

            modelBuilder.Entity("TestBackEnd.src.Models.Rental", b =>
                {
                    b.HasOne("TestBackEnd.src.Models.Deliverer", "Deliverer")
                        .WithMany("Rentals")
                        .HasForeignKey("DelivererId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestBackEnd.src.Models.Motorcycle", "Motorcycle")
                        .WithMany("Rentals")
                        .HasForeignKey("MotorcycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestBackEnd.src.Models.RentalType", "RentalType")
                        .WithMany("Rentals")
                        .HasForeignKey("RentalTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deliverer");

                    b.Navigation("Motorcycle");

                    b.Navigation("RentalType");
                });

            modelBuilder.Entity("TestBackEnd.src.Models.Deliverer", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("TestBackEnd.src.Models.Motorcycle", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("TestBackEnd.src.Models.RentalType", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
