services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit_mq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user123
      RABBITMQ_DEFAULT_PASS: user@123


  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: TestBackEndDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data


volumes:
  postgres_data:
  mongo_data: